name: Register check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  register-integrity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Run setup.py
        run: |
          python3 setup.py

      - name: Run test.py
        env:
          # test.py configures these itself, but you can override if needed
          WS_REAL_DATA: "1"
          REGISTER_DATA_PATH: ${{ github.workspace }}
        run: |
          python3 test.py
